// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt8uFSCb6Ysf7SGJrD9JjK1NtV6vO06ac',
    appId: '1:731954077807:web:cab3803121989c09bb6d9a',
    messagingSenderId: '731954077807',
    projectId: 'teachertracker-6879d',
    authDomain: 'teachertracker-6879d.firebaseapp.com',
    storageBucket: 'teachertracker-6879d.firebasestorage.app',
    measurementId: 'G-R7FFVZ2NHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ydtz2FqtHYpo_tQ6FIILBiFjWVTp_6s',
    appId: '1:731954077807:android:4ef6a2e596576814bb6d9a',
    messagingSenderId: '731954077807',
    projectId: 'teachertracker-6879d',
    storageBucket: 'teachertracker-6879d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByviAVewwAOwJN-AX5G8CMbg6olL2iZJ4',
    appId: '1:731954077807:ios:af64d89beb8d085abb6d9a',
    messagingSenderId: '731954077807',
    projectId: 'teachertracker-6879d',
    storageBucket: 'teachertracker-6879d.firebasestorage.app',
    iosBundleId: 'com.example.teacherTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByviAVewwAOwJN-AX5G8CMbg6olL2iZJ4',
    appId: '1:731954077807:ios:af64d89beb8d085abb6d9a',
    messagingSenderId: '731954077807',
    projectId: 'teachertracker-6879d',
    storageBucket: 'teachertracker-6879d.firebasestorage.app',
    iosBundleId: 'com.example.teacherTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt8uFSCb6Ysf7SGJrD9JjK1NtV6vO06ac',
    appId: '1:731954077807:web:d93a479581617f7dbb6d9a',
    messagingSenderId: '731954077807',
    projectId: 'teachertracker-6879d',
    authDomain: 'teachertracker-6879d.firebaseapp.com',
    storageBucket: 'teachertracker-6879d.firebasestorage.app',
    measurementId: 'G-H0S3162SLL',
  );
}
